# Generated by Django 4.2.7 on 2023-11-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='summ',
            field=models.PositiveIntegerField(default=2, verbose_name='Сумма'),
        ),
    ]
