# Generated by Django 4.2.7 on 2023-11-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_transactions_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='summ',
            field=models.PositiveIntegerField(verbose_name='Сумма'),
        ),
    ]
